--- 
:wallpaper_url: http://www.theotaku.com/wallpapers/view/203374/beautiful_day_dance%2521
:base_color: "#a8b7b5"
:background_color: rgba(67, 73, 72, 0.4)
:link_color: "#869291"
:link_hover_color: "#b9c9c7"
:link_active_color: "#76807f"
